SESSION_KEY               = ENV['GILM_SESSION_KEY']    || 'GILM_SESSION'
SESSION_SECRET            = ENV['GILM_SESSION_SECRET'] || ''
GITHUB_CLIENT_ID          = ENV['GILM_GITHUB_CLIENT_ID']
GITHUB_CLIENT_SECRET      = ENV['GILM_GITHUB_CLIENT_SECRET']
